Update Decidim 0.25 to take fix in the seeds
CodiTramuntana/decidim-jaen-app pull request #4
Opened 2022-04-05 15:41 UTC by tramuntanal

Update Decidim 0.25 to take fix in the seeds.
It also has some configuration modifications.

2022-04-06 13:37 UTC, laurajaime requested changes
Only one thing about npm.

2022-04-06 13:37 UTC, laurajaime commented on README.md
> +yarn install
Decidim use `npm` and maybe is a good idea use it here too.

2022-04-06 16:07 UTC, tramuntanal commented on README.md
> +yarn install
I totally agree, I've just updated the doc

2022-04-08 06:05 UTC, LauraJaimeC approved these changes

2022-04-08 07:16 UTC, merged