Update decidim version to 0.26
CodiTramuntana/decidim-jaen-app pull request #8
Opened 2022-05-11 12:55 UTC by ClaudiaMoPr

This PR upgrades the application to Decidim version 0.26.
Release notes: https://github.com/decidim/decidim/releases/tag/v0.26.0

On deploy it will require to execute the following commands:

- Upgrade server's Ruby version to 2.7.5
- For locked users are present in global search, to update the search and make them disappear, Run in a bin/rails console or create a migration with:
  `Decidim::User.find_each(&:try_update_index_for_search_resource)`
- For fixing statistic in comments. There's a rake task that you need to run:
  `bin/rails decidim_comments:update_participatory_process_in_comments`
- For Base64 images migration run the following task:
  `bin/rails decidim:active_storage_migrations:migrate_inline_images_to_active_storage[admin_email]`

2022-05-16 06:38 UTC, LauraJaimeC approved these changes

2022-05-23 06:38 UTC, LauraJaimeC requested changes
I do it QA but there is a missing translation, can you check it?

2022-05-23 06:38 UTC, LauraJaimeC commented
@ClaudiaMoPr there is the error:

![image](https://user-images.githubusercontent.com/75725233/169758553-dcf1bf81-f74a-4598-b77a-580a0957e985.png)

2022-07-06 06:33 UTC, LauraJaimeC approved these changes

2022-07-06 10:32 UTC, tramuntanal requested changes
Just a couple of things to check please

2022-07-06 10:32 UTC, tramuntanal commented on Gemfile
> -gem "delayed_job_active_record"
why remove delayed_jobs?

2022-07-06 10:32 UTC, tramuntanal commented on Gemfile
> -gem "whenever"
why remove whenever?

2022-07-06 11:17 UTC, tramuntanal approved these changes
Good thanks!

2022-07-11 06:22 UTC, merged